// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Uint8List> formatChallenge({
  required List<int> random,
  required PlatformInt64 timestamp,
}) => RustLib.instance.api.crateApiFormatChallenge(
  random: random,
  timestamp: timestamp,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MldsaKey>>
abstract class MldsaKey implements RustOpaqueInterface {
  static Future<MldsaKey> fromBytes({required List<int> bytes}) =>
      RustLib.instance.api.crateApiMldsaKeyFromBytes(bytes: bytes);

  static Future<MldsaKey> generate() =>
      RustLib.instance.api.crateApiMldsaKeyGenerate();

  Future<Uint8List> getPublicKey();

  Future<Uint8List> sign({required List<int> message});

  Future<Uint8List> toBytes();
}
