syntax = "proto3";

package arbiter.operator.evm;

import "evm.proto";
import "google/protobuf/empty.proto";

message SignTransactionRequest {
  int32 client_id = 1;
  arbiter.evm.EvmSignTransactionRequest request = 2;
}

message Request {
  oneof payload {
    google.protobuf.Empty wallet_create = 1;
    google.protobuf.Empty wallet_list = 2;
    arbiter.evm.EvmGrantCreateRequest grant_create = 3;
    arbiter.evm.EvmGrantDeleteRequest grant_delete = 4;
    arbiter.evm.EvmGrantListRequest grant_list = 5;
    SignTransactionRequest sign_transaction = 6;
  }
}

message Response {
  oneof payload {
    arbiter.evm.WalletCreateResponse wallet_create = 1;
    arbiter.evm.WalletListResponse wallet_list = 2;
    arbiter.evm.EvmGrantCreateResponse grant_create = 3;
    arbiter.evm.EvmGrantDeleteResponse grant_delete = 4;
    arbiter.evm.EvmGrantListResponse grant_list = 5;
    arbiter.evm.EvmSignTransactionResponse sign_transaction = 6;
  }
}
