
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.OpenDevicePartnership]
url = "https://raw.githubusercontent.com/OpenDevicePartnership/rust-crate-audits/refs/heads/main/audits.toml"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.asn1-rs]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.asn1-rs-derive]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.asn1-rs-impl]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.axum]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.axum-core]]
version = "0.5.6"
criteria = "safe-to-deploy"

[[exemptions.backtrace-ext]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.bb8]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.55"
criteria = "safe-to-deploy"

[[exemptions.chacha20]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.43"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "5.0.0-pre.6"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek-derive]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.21.3"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.21.3"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.21.3"
criteria = "safe-to-deploy"

[[exemptions.dashmap]]
version = "6.1.0"
criteria = "safe-to-deploy"

[[exemptions.data-encoding]]
version = "2.10.0"
criteria = "safe-to-deploy"

[[exemptions.der-parser]]
version = "10.0.0"
criteria = "safe-to-deploy"

[[exemptions.diesel]]
version = "2.3.6"
criteria = "safe-to-deploy"

[[exemptions.diesel-async]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.diesel_derives]]
version = "2.3.7"
criteria = "safe-to-deploy"

[[exemptions.diesel_migrations]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.diesel_table_macro_syntax]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.11.0-rc.11"
criteria = "safe-to-deploy"

[[exemptions.downcast-rs]]
version = "2.0.2"
criteria = "safe-to-deploy"

[[exemptions.dsl_auto_type]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.ed25519]]
version = "3.0.0-rc.4"
criteria = "safe-to-deploy"

[[exemptions.ed25519-dalek]]
version = "3.0.0-pre.6"
criteria = "safe-to-deploy"

[[exemptions.find-msvc-tools]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.fixedbitset]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.fs_extra]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.hybrid-array]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.hyper-timeout]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.65"
criteria = "safe-to-deploy"

[[exemptions.is_ci]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.85"
criteria = "safe-to-deploy"

[[exemptions.kameo]]
version = "0.19.2"
criteria = "safe-to-deploy"

[[exemptions.kameo_macros]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.libsqlite3-sys]]
version = "0.35.0"
criteria = "safe-to-deploy"

[[exemptions.matchit]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.memsafe]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.miette]]
version = "7.6.0"
criteria = "safe-to-deploy"

[[exemptions.miette-derive]]
version = "7.6.0"
criteria = "safe-to-deploy"

[[exemptions.migrations_internals]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.migrations_macros]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.multimap]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.oid-registry]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.owo-colors]]
version = "4.2.3"
criteria = "safe-to-deploy"

[[exemptions.pem]]
version = "3.0.6"
criteria = "safe-to-deploy"

[[exemptions.petgraph]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pulldown-cmark]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.rcgen]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.18"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.14"
criteria = "safe-to-deploy"

[[exemptions.rsqlite-vfs]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.rusticata-macros]]
version = "4.1.0"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.23.36"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.14.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.103.9"
criteria = "safe-to-deploy"

[[exemptions.scoped-futures]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.secrecy]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.27"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.11.0-rc.5"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.8"
criteria = "safe-to-deploy"

[[exemptions.signature]]
version = "3.0.0-rc.10"
criteria = "safe-to-deploy"

[[exemptions.simd-adler32]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.smlang]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.smlang-macros]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.sqlite-wasm-rs]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.string_morph]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.supports-color]]
version = "3.0.2"
criteria = "safe-to-deploy"

[[exemptions.supports-hyperlinks]]
version = "3.2.0"
criteria = "safe-to-deploy"

[[exemptions.supports-unicode]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.25.0"
criteria = "safe-to-deploy"

[[exemptions.terminal_size]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.26.4"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.44"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.36"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.22"
criteria = "safe-to-run"

[[exemptions.typenum]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.108"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.108"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.108"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.x509-parser]]
version = "0.18.1"
criteria = "safe-to-deploy"

[[exemptions.yasna]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd]]
version = "0.13.3"
criteria = "safe-to-deploy"

[[exemptions.zstd-safe]]
version = "7.2.4"
criteria = "safe-to-deploy"

[[exemptions.zstd-sys]]
version = "2.0.16+zstd.1.5.7"
criteria = "safe-to-deploy"
