[package]
name = "arbiter-server"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.3.6", features = ["sqlite", "uuid", "time", "chrono", "serde_json"] }
diesel-async = { version = "0.7.4", features = ["sqlite", "tokio", "migrations", "pool", "deadpool"] }
tracing.workspace = true
tonic.workspace = true
tokio.workspace = true