syntax = "proto3";

package arbiter.auth;

import "google/protobuf/timestamp.proto";

message AuthChallengeRequest {
  bytes pubkey = 1;
  optional string bootstrap_token = 2;
}

message AuthChallenge {
  bytes pubkey = 1;
  bytes nonce = 2;
  google.protobuf.Timestamp minted = 3;
}

message AuthChallengeSolution {
  AuthChallenge challenge = 1;
  bytes signature = 2;
}

message AuthOk {}

message ClientMessage {
  oneof payload {
    AuthChallengeRequest auth_challenge_request = 1;
    AuthChallengeSolution auth_challenge_solution = 2;
  }
}

message ServerMessage {
  oneof payload {
    AuthChallenge auth_challenge = 1;
    AuthOk auth_ok = 2;
  }
}
