syntax = "proto3";

package arbiter.user_agent;

import "user_agent/auth.proto";
import "user_agent/evm.proto";
import "user_agent/sdk_client.proto";
import "user_agent/vault/vault.proto";

message UserAgentRequest {
  int32 id = 16;
  oneof payload {
    auth.Request auth = 1;
    vault.Request vault = 2;
    evm.Request evm = 3;
    sdk_client.Request sdk_client = 4;
  }
}

message UserAgentResponse {
  optional int32 id = 16;
  oneof payload {
    auth.Response auth = 1;
    vault.Response vault = 2;
    evm.Response evm = 3;
    sdk_client.Response sdk_client = 4;
  }
}
